name: heGUI
channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- tk=8.6.11
- pyqt=5.15.7
- pip
- pip:
    - magicgui[pyqt5]
    - git+https://github.com/WEHI-labatlab/mibilib
    - napari[all]==0.4.16
    - python-dotenv==0.19.0
    - scikit-image==0.19.3
    - imagecodecs==2021.8.26
